services:
  vllm-openai:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    environment:
      # - VLLM_LOGGING_LEVEL=DEBUG
      - VLLM_CONFIGURE_LOGGING=1
    volumes:
      - ~/.models/:/models
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    command: 
      # - --model=/models/gpt-oss-20b-urdf
      - --model=openai/gpt-oss-20b
      - --enable-log-requests
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  gpu:
restart: unless-stopped
    build: .
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - ./:/workspace
      - ~/.models/:/models
      - ~/.cache/huggingface:/root/.cache/huggingface
